name: task_app_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.2.0
  get_it: ^8.0.3
  fl_chart: ^0.64.0
  provider: ^6.1.4
  mask_text_input_formatter: ^2.5.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/imagens/logo.png
