// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADHvyUr4a4yhdC8B7H6p400__HRJPaHbE',
    appId: '1:137750917372:web:d752e595f3a6e1cdb4e779',
    messagingSenderId: '137750917372',
    projectId: 'task-app-flutter-d8965',
    authDomain: 'task-app-flutter-d8965.firebaseapp.com',
    storageBucket: 'task-app-flutter-d8965.firebasestorage.app',
    measurementId: 'G-DNZJFT4K8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRiLXMaWJpZ0CA8u3bX1sb9ePuHA9ocfY',
    appId: '1:137750917372:android:c4d17aa1415ccaa4b4e779',
    messagingSenderId: '137750917372',
    projectId: 'task-app-flutter-d8965',
    storageBucket: 'task-app-flutter-d8965.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ2m1jDLJpdtOU74-9lwOE4vFf-GhGW9E',
    appId: '1:137750917372:ios:73d304a3fe8d773bb4e779',
    messagingSenderId: '137750917372',
    projectId: 'task-app-flutter-d8965',
    storageBucket: 'task-app-flutter-d8965.firebasestorage.app',
    iosBundleId: 'com.example.taskAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ2m1jDLJpdtOU74-9lwOE4vFf-GhGW9E',
    appId: '1:137750917372:ios:73d304a3fe8d773bb4e779',
    messagingSenderId: '137750917372',
    projectId: 'task-app-flutter-d8965',
    storageBucket: 'task-app-flutter-d8965.firebasestorage.app',
    iosBundleId: 'com.example.taskAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADHvyUr4a4yhdC8B7H6p400__HRJPaHbE',
    appId: '1:137750917372:web:b3e73c925e7754b9b4e779',
    messagingSenderId: '137750917372',
    projectId: 'task-app-flutter-d8965',
    authDomain: 'task-app-flutter-d8965.firebaseapp.com',
    storageBucket: 'task-app-flutter-d8965.firebasestorage.app',
    measurementId: 'G-02JDBNSZDX',
  );
}
